version: "2.1"
services:
  my-ddclient:
    image: lscr.io/linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
    volumes:
      - ./config:/config
    restart: unless-stopped
